#include "DMA1.h"

void DMASTREAMINIT(DMAV2_BYTES* DMASEL,U8 STR,U32 CRVAL,U32 FCRVAL,U32 NDTRVAL,U32 PARVAL,U32 M0ARVAL,U32 M1ARVAL)
{
   DMASEL->STREAM[STR].CR.VALUE=(CRVAL);
   DMASEL->STREAM[STR].FCR.VALUE=(FCRVAL);
   DMASEL->STREAM[STR].NDTR.VALUE=(NDTRVAL);
   DMASEL->STREAM[STR].PAR.VALUE=(PARVAL);
   DMASEL->STREAM[STR].M0AR.VALUE=(M0ARVAL);
   DMASEL->STREAM[STR].M1AR.VALUE=(M1ARVAL);
}
//#define DMA2_STREAMEN(STR) DMA2.STREAM[STR].CR.BIT.EN=1;
//#define DMA2_STREAMDIS(STR) DMA2.STREAM[STR].CR.BIT.EN=0;\
        while(BB_ACCESS((DMA2_BASE+0x10+(STR*24)),0));

void DMASTREAMENCMD(DMAV2_BYTES* DMASEL,U8 STR,State CMD)
{
    if(CMD)
    {
       DMASEL->STREAM[STR].CR.BIT.EN=1;
    }
    else
    {
       DMASEL->STREAM[STR].CR.BIT.EN=0;
       while(BB_ACCESS(((U32)&DMASEL+0x10+(STR*24)),0));
    }
}

