#include "DMAV1.h"

void DMA_CHDIS(DMAV1_BYTES *DMA,U8 CHANNEL)
{
  DMA->CH[((CHANNEL)-1)].CCR.BIT.EN=0;
}

void DMA_CHEN(DMAV1_BYTES *DMA,U8 CHANNEL)
{
  DMA->CH[((CHANNEL)-1)].CCR.BIT.EN=1;
}
void DMA_CHINIT(DMAV1_BYTES *DMA,U32 CHENEL,U32 CONFIG,U32 NUMBER,U32 PADDR,U32 MADDR)
{
  DMA->CH[((CHENEL)-1)].CCR.VALUE=(CONFIG);
  DMA->CH[((CHENEL)-1)].CNDTR.VALUE=(NUMBER);
  DMA->CH[((CHENEL)-1)].CPAR.VALUE=(PADDR);
  DMA->CH[((CHENEL)-1)].CMAR.VALUE=(MADDR);
}