#include "STM32/PERIPH/RCC/RCCF051X.h"

#if defined(STM32F051X)

CMDRES HSICMD(U16 TIMEOUT,State CMD)
{
   RCC.CR.BIT.HSION=CMD;
   while((TIMEOUT--)&&(RCC.CR.BIT.HSIRDY!=CMD));
   if(TIMEOUT){return NORMAL;}else{return TIMEOUTERR;}
}

CMDRES HSI14CMD(U16 TIMEOUT,State CMD)
{
   RCC.CR2.BIT.HSI14ON=CMD;
   while((TIMEOUT--)&&(RCC.CR2.BIT.HSI14RDY!=CMD));
   if(TIMEOUT){return NORMAL;}else{return TIMEOUTERR;}
}

CMDRES PLLCMD(U16 TIMEOUT,State CMD)
{
   RCC.CR.BIT.PLLON=CMD;
   while((TIMEOUT--)&&(RCC.CR.BIT.PLLRDY!=CMD));
   if(TIMEOUT){return NORMAL;}else{return TIMEOUTERR;}
}

void MAINPLLINIT(PLL_SRC SRC,U16 PLLMUL)
{
  RCC.CFGR.BIT.PLLSRC=SRC;
  RCC.CFGR.BIT.PLLMUL=(PLLMUL-2);
}

void APBAHBDIV(APB_DIV APB,AHB_DIV AHB)
{
  RCC.CFGR.BIT.PPRE=APB;
  RCC.CFGR.BIT.HPRE=AHB;
}

void SETCLKSOURCE(CLKSRC SRC)
{
	RCC.CFGR3.VALUE=SRC;
}


CMDRES SYSCLKSW(SYSSRC SOURSE,U16 TIMEOUT)
{
  RCC.CFGR.BIT.SW=SOURSE;
  while(TIMEOUT--)
  {
    if(RCC.CFGR.BIT.SW==RCC.CFGR.BIT.SWS)
    {
      return NORMAL;
    }
  }
  return TIMEOUTERR;
}

#endif//defined(STM32F051X)
